version: '2.1'
services:
  users-db:
    container_name: users-db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: users-db
      MYSQL_USER: sa
      MYSQL_PASSWORD: 123
    ports:
      - "3307:3306"
  users-ms:
    container_name: users-ms
    build: .
    command: bash -c "sleep 10 && rake db:drop db:create db:migrate db:seed && bundle exec rails s -p 3001 -b '0.0.0.0'"
    ports:
      - "3001:3001"
    links:
      - users-db:sql_srv
    depends_on:
      - users-db

